### ISSUE TITLE
Issue building this project on 4.16

### ISSUE THREAD

**Issue by ghost** [mortennost/GOAP#1]
Hi,

I've attempted to compile this project, however I get errors:

>C:\Users\RJ\Downloads\GOAP-master\Source\GOAP\GOAPState.h(29): error C4596: 'IsGOAPStateSatisfied': illegal qualified name in member declaration
1>C:\Users\RJ\Downloads\GOAP-master\Source\GOAP\GOAPState.h(49): error C4596: 'IsStateSatisfied': illegal qualified name in member declaration
1>C:\Users\RJ\Downloads\GOAP-master\Source\GOAP\GOAPState.h(66): error C4596: 'SetState': illegal qualified name in member declaration
1>C:\Users\RJ\Downloads\GOAP-master\Source\GOAP\GOAPState.h(29): error C4596: 'IsGOAPStateSatisfied': illegal qualified name in member declaration
1>C:\Users\RJ\Downloads\GOAP-master\Source\GOAP\GOAPState.h(49): error C4596: 'IsStateSatisfied': illegal qualified name in member declaration
1>C:\Users\RJ\Downloads\GOAP-master\Source\GOAP\GOAPState.h(66): error C4596: 'SetState': illegal qualified name in member declaration

Your project seems promising so I hope you can fix this. I wonder how fit this project is
to be integrated into a UE4 project?

**Comment by mortennost** [comment]
Hi.
This project's implementation is a bit old and not maintained at all. It was just a hobby project trying stuff out.
Anyway, I think you should get it to compile by removing the "FGoapState::" part before the function name:
"bool FGOAPState::IsStateSatisfied(const uint8 stateKey, const bool stateValue)"
..should be like this:
"bool IsStateSatisfied(const uint8 stateKey, const bool stateValue)"

A header file shouldn't have a class identifier/qualified name before the in-line function/definition. It's just that Visual Studio allows it, and I guess at one point the Unreal HeaderTool didn't care either.
However, fix the function definition like stated above for the whole FGoapState class (and any other header file with the same issue), and it should compile for you. 

Hope that helps.

**Comment by ghost** [comment]
Yes it does compile now, thanks!
